import 'package:flutter/cupertino.dart';

const KMainColor = Color(0xFFFFC12F);
const KSecondary = Color(0xFFFFE6AC);
const KProductCollection='Products';
const KProductName="ProductName";
const KProductDes='ProductDes';
const KProductLocation="ProductLocation";
const KProductPrice="ProductPrice";
const KProductCategory="ProductCategory";
const KUnActiveColor=Color(0xFFC1BDB8);
const KTshirts='t-shirts';
const KShoes='shoes';
const KJackets='jackets';
const KTrousers='trousers';
const KOrders="orders";
const KOrdersdetailes="Orderdetails";
const KorderPrice="TotalPriceprice";
const KAddress="Address";
const KKeepmeLogin="KeepMelogin";
const KQuantity="Quantity";